### ISSUE TITLE
Part of the answer weirdly written

### ISSUE THREAD

**Issue by ZainGithub12** [YassKhazzan/openperplex_front#2]
![Screenshot_20240805_171636_Chrome.jpg](https://github.com/user-attachments/assets/2c3744a0-809c-440c-9a9e-4d083f45dda0)

@YassKhazzan, As you can see, where it says raised capital in answer, it's written in LaTeX and weirdly long with no spaces in between.

**Comment by ZainGithub12** [comment]
![Screenshot_20240805_172101_Chrome.jpg](https://github.com/user-attachments/assets/a96d32b1-51af-442d-882c-4355f3c239e6)

Tried again.

**Comment by YassKhazzan** [comment]
Model hallucinations occasionally occur when using Groq. This is an inherent issue that can sometimes arise.
