### ISSUE TITLE
Error occuring

### ISSUE THREAD

**Issue by ZainGithub12** [YassKhazzan/openperplex_front#4]
![Screenshot_20240807_180155_Chrome.jpg](https://github.com/user-attachments/assets/7885b842-31f4-463a-97f2-0770ba9b3a36)

@YassKhazzan, As you can see, OpenPerplex is having issues at the moment. Is this because an update is happening again? And if that's the case, will this always happen when there's updates?

**Comment by YassKhazzan** [comment]
I'm releasing a new version that now includes rate limit handling. I had to temporarily stop the server because someone was using cURL to send 100 requests per minute. The updated version is being released now to address this issue
