### ISSUE TITLE
Issue in response

### ISSUE THREAD

**Issue by ZainGithub12** [YassKhazzan/openperplex_front#5]
@YassKhazzan I said, how call arc from the browser company compares to other assistants like inflections PI ai, and it responded with, "Comparing Call AI" it was meant to say "Comparing call Arc" 
Image below:
![Screenshot_20240903_165426_Chrome.jpg](https://github.com/user-attachments/assets/465c3f36-cd89-474c-b9ed-30b5f5252749)

**Comment by YassKhazzan** [comment]
hello, couldn't replicate this !! 
<img width="1016" alt="Capture d’écran 2024-09-03 à 21 08 11" src="https://github.com/user-attachments/assets/64d4d5c4-f895-4c0c-8469-2e39509ad643">

**Comment by ZainGithub12** [comment]
@YassKhazzan, When I ask the same thing a different way, including the name (Arc Search), in this case, it understands my question better. So I will do this with any other query. Should I close this as resolved?  
![Screenshot_20240903_231916_Chrome.jpg](https://github.com/user-attachments/assets/0d341a78-30a0-4268-88c0-19d1076f817f)
